/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/securities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Securities */
        get: operations["list_securities_api_securities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** IndexQuote */
        IndexQuote: {
            /** Yahoo Ticker */
            yahoo_ticker: string;
            /** Name */
            name: string;
            /** Price */
            price: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** As Of */
            as_of: string | null;
        };
        /** JobStatus */
        JobStatus: {
            /** Job */
            job: string;
            /** Last Success At */
            last_success_at: string | null;
            /** Last Error At */
            last_error_at: string | null;
            /** Last Error */
            last_error: string | null;
            /** Last Count */
            last_count: number;
        };
        /** SecurityItem */
        SecurityItem: {
            /** Id */
            id: number;
            /** Yahoo Ticker */
            yahoo_ticker: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Market */
            market: string;
            /** Country */
            country: string | null;
            /** Sector */
            sector: string | null;
            /** Eligibility */
            eligibility: string;
            /** Price */
            price: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** As Of */
            as_of: string | null;
        };
        /** SecurityList */
        SecurityList: {
            /** Items */
            items: components["schemas"]["SecurityItem"][];
            /** Total */
            total: number;
        };
        /** StatusResponse */
        StatusResponse: {
            /** Market Open */
            market_open: boolean;
            /** Jobs */
            jobs: components["schemas"]["JobStatus"][];
            /** Indices */
            indices: components["schemas"]["IndexQuote"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_securities_api_securities_get: {
        parameters: {
            query?: {
                q?: string | null;
                kind?: ("stock" | "etf" | "index") | null;
                eligibility?: ("eligible" | "a_verifier" | "non_eligible") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
}
