/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/securities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Securities */
        get: operations["list_securities_api_securities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/securities/{security_id}/eligibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Eligibility */
        patch: operations["update_eligibility_api_securities__security_id__eligibility_patch"];
        trace?: never;
    };
    "/api/securities/{security_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Security */
        get: operations["get_security_api_securities__security_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/securities/{security_id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_api_securities__security_id__history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/securities/{security_id}/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get News */
        get: operations["get_news_api_securities__security_id__news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/securities/{security_id}/simulate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Simulate */
        get: operations["simulate_api_securities__security_id__simulate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Status */
        get: operations["get_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/screener": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Screener */
        get: operations["get_screener_api_screener_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rankings/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Top */
        get: operations["get_top_api_rankings_top_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rankings/movers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Movers */
        get: operations["get_movers_api_rankings_movers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/market/heatmap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Heatmap */
        get: operations["get_heatmap_api_market_heatmap_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fees/estimate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Estimate Fee */
        get: operations["estimate_fee_api_fees_estimate_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/{security_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Add Favorite */
        put: operations["add_favorite_api_favorites__security_id__put"];
        post?: never;
        /** Remove Favorite */
        delete: operations["remove_favorite_api_favorites__security_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Settings */
        get: operations["read_settings_api_settings_get"];
        /** Update Settings */
        put: operations["update_settings_api_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Orders */
        get: operations["get_orders_api_orders_get"];
        put?: never;
        /** Create Order */
        post: operations["create_order_api_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Order */
        put: operations["update_order_api_orders__order_id__put"];
        post?: never;
        /** Delete Order */
        delete: operations["delete_order_api_orders__order_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/counter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Counter */
        get: operations["get_counter_api_orders_counter_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio */
        get: operations["get_portfolio_api_portfolio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/portfolio/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Portfolio History */
        get: operations["get_portfolio_history_api_portfolio_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Assistant Settings */
        get: operations["read_assistant_settings_api_assistant_settings_get"];
        /** Update Assistant Settings */
        put: operations["update_assistant_settings_api_assistant_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_api_assistant_conversations_get"];
        put?: never;
        /** Create Conversation */
        post: operations["create_conversation_api_assistant_conversations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversation */
        get: operations["get_conversation_api_assistant_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_api_assistant_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/assistant/conversations/{conversation_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send Message */
        post: operations["send_message_api_assistant_conversations__conversation_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecasts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Forecasts */
        get: operations["list_forecasts_api_forecasts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecasts/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signal Statistics */
        get: operations["signal_statistics_api_forecasts_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/forecasts/track-record": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track Record */
        get: operations["track_record_api_forecasts_track_record_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/securities/{security_id}/forecast": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Security Forecast */
        get: operations["security_forecast_api_securities__security_id__forecast_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seo/robots.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Robots */
        get: operations["robots_api_seo_robots_txt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seo/sitemap.xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sitemap */
        get: operations["sitemap_api_seo_sitemap_xml_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/seo/llms.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Llms */
        get: operations["llms_api_seo_llms_txt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssistantSettingsOut */
        AssistantSettingsOut: {
            /** Configured */
            configured: boolean;
            /** Source */
            source: ("settings" | "env") | null;
            /** Model */
            model: string;
            /** Models */
            models: components["schemas"]["ModelOut"][];
        };
        /** AssistantSettingsUpdate */
        AssistantSettingsUpdate: {
            /** Api Key */
            api_key?: string | null;
            /**
             * Remove Key
             * @default false
             */
            remove_key: boolean;
            /** Model */
            model: string;
        };
        /** BacktestOut */
        BacktestOut: {
            /** Days */
            days: number;
            /** Picks */
            picks: number;
            /** Hit Rate */
            hit_rate: number;
            /** Hit After Fees */
            hit_after_fees: number;
            /** Mean Return */
            mean_return: number;
            /** Mean After Fees */
            mean_after_fees: number;
            /** Mean Excess */
            mean_excess: number;
            /** Baseline Mean */
            baseline_mean: number;
            /** Edge */
            edge: number;
        };
        /** Bar */
        Bar: {
            /** Time */
            time: string | number;
            /** Open */
            open: number | null;
            /** High */
            high: number | null;
            /** Low */
            low: number | null;
            /** Close */
            close: number;
            /** Volume */
            volume: number | null;
        };
        /** ComponentOut */
        ComponentOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Points */
            points: number;
            /** Max Points */
            max_points: number;
            /** Message */
            message: string;
            /** Group */
            group: string;
        };
        /** ConversationDetail */
        ConversationDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Security Id */
            security_id: number | null;
            /** Security Name */
            security_name: string | null;
            /** Security Symbol */
            security_symbol: string | null;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Messages */
            messages: components["schemas"]["MessageOut"][];
        };
        /** ConversationIn */
        ConversationIn: {
            /** Security Id */
            security_id?: number | null;
        };
        /** ConversationOut */
        ConversationOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /** Security Id */
            security_id: number | null;
            /** Security Name */
            security_name: string | null;
            /** Security Symbol */
            security_symbol: string | null;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Cost Usd */
            cost_usd: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** CounterOut */
        CounterOut: {
            /** Year */
            year: number;
            /** Count */
            count: number;
            /** Min Orders */
            min_orders: number;
            /** Remaining */
            remaining: number;
            /** Expected By Now */
            expected_by_now: number;
            /** Behind */
            behind: boolean;
            /** Penalty Fee */
            penalty_fee: number;
        };
        /** EligibilityUpdate */
        EligibilityUpdate: {
            /** Override */
            override: ("eligible" | "non_eligible") | null;
        };
        /** FeeEstimate */
        FeeEstimate: {
            /** Amount */
            amount: number;
            /** Fee */
            fee: number;
            /** Rate */
            rate: number;
        };
        /** FeeTierIn */
        FeeTierIn: {
            /** Up To */
            up_to?: number | null;
            /** Rate */
            rate: number;
        };
        /** ForecastListOut */
        ForecastListOut: {
            /** As Of */
            as_of: string | null;
            /** Round Trip Cost */
            round_trip_cost: number | null;
            /** Rows */
            rows: components["schemas"]["ForecastRowOut"][];
        };
        /** ForecastRowOut */
        ForecastRowOut: {
            security: components["schemas"]["ForecastSecurityOut"];
            /** Signals */
            signals: components["schemas"]["SignalOut"][];
            /** Horizons */
            horizons: {
                [key: string]: components["schemas"]["HorizonForecastOut"] | null;
            };
        };
        /** ForecastSecurityOut */
        ForecastSecurityOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Symbol */
            symbol: string;
            /** Market */
            market: string;
            /** Eligibility */
            eligibility: string;
            /** Price */
            price: number | null;
            /** Change Pct */
            change_pct: number | null;
        };
        /** FundamentalsOut */
        FundamentalsOut: {
            /** Pe */
            pe: number | null;
            /** Eps */
            eps: number | null;
            /** Earnings Growth */
            earnings_growth: number | null;
            /** Revenue Growth */
            revenue_growth: number | null;
            /** Debt To Equity */
            debt_to_equity: number | null;
            /** Profit Margin */
            profit_margin: number | null;
            /** Dividend Yield */
            dividend_yield: number | null;
            /** Market Cap */
            market_cap: number | null;
            /** Currency */
            currency: string | null;
            /** Updated At */
            updated_at: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HeatmapItem */
        HeatmapItem: {
            /** Id */
            id: number;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Sector */
            sector: string;
            /** Market Cap Eur */
            market_cap_eur: number;
            /** Change Pct */
            change_pct: number;
        };
        /** HistoryOut */
        HistoryOut: {
            /** Period */
            period: string;
            /** Intraday */
            intraday: boolean;
            /** Bars */
            bars: components["schemas"]["Bar"][];
            /** Sma50 */
            sma50: components["schemas"]["LinePoint"][];
            /** Sma200 */
            sma200: components["schemas"]["LinePoint"][];
            /** Rsi */
            rsi: components["schemas"]["LinePoint"][];
            /** Macd */
            macd: components["schemas"]["MacdPoint"][];
        };
        /** HistoryPointOut */
        HistoryPointOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Value */
            value: number;
            /** Invested */
            invested: number;
        };
        /** HorizonForecastOut */
        HorizonForecastOut: {
            /** Expected Return */
            expected_return: number;
            /** Prob Up */
            prob_up: number;
            /** Reliability */
            reliability: string;
            /** Rank */
            rank: number;
        };
        /** IndexQuote */
        IndexQuote: {
            /** Id */
            id: number;
            /** Yahoo Ticker */
            yahoo_ticker: string;
            /** Name */
            name: string;
            /** Price */
            price: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** As Of */
            as_of: string | null;
        };
        /** JobStatus */
        JobStatus: {
            /** Job */
            job: string;
            /** Last Success At */
            last_success_at: string | null;
            /** Last Error At */
            last_error_at: string | null;
            /** Last Error */
            last_error: string | null;
            /** Last Count */
            last_count: number;
        };
        /** LinePoint */
        LinePoint: {
            /** Time */
            time: string;
            /** Value */
            value: number;
        };
        /** MacdPoint */
        MacdPoint: {
            /** Time */
            time: string;
            /** Macd */
            macd: number;
            /** Signal */
            signal: number;
            /** Histogram */
            histogram: number;
        };
        /** MessageIn */
        MessageIn: {
            /** Content */
            content: string;
        };
        /** MessageOut */
        MessageOut: {
            /** Id */
            id: number;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant";
            /** Content */
            content: string;
            /** Tools */
            tools: string[];
            /** Interrupted */
            interrupted: boolean;
            /** Error */
            error: string | null;
            /** Cost Usd */
            cost_usd: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ModelOut */
        ModelOut: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** Movers */
        Movers: {
            /** Gainers */
            gainers: components["schemas"]["ScreenerRow"][];
            /** Losers */
            losers: components["schemas"]["ScreenerRow"][];
        };
        /** NewsOut */
        NewsOut: {
            /** Title */
            title: string;
            /** Url */
            url: string;
            /** Publisher */
            publisher: string | null;
            /** Published At */
            published_at: string | null;
        };
        /** OrderIn */
        OrderIn: {
            /** Security Id */
            security_id: number;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /**
             * Side
             * @enum {string}
             */
            side: "buy" | "sell";
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: number;
            /** Fee */
            fee?: number | null;
            /** Note */
            note?: string | null;
        };
        /** OrderOut */
        OrderOut: {
            /** Id */
            id: number;
            /** Security Id */
            security_id: number;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /**
             * Trade Date
             * Format: date
             */
            trade_date: string;
            /** Side */
            side: string;
            /** Quantity */
            quantity: number;
            /** Unit Price */
            unit_price: number;
            /** Fee */
            fee: number;
            /** Amount */
            amount: number;
            /** Note */
            note: string | null;
        };
        /** PortfolioOut */
        PortfolioOut: {
            /** Total Value */
            total_value: number;
            /** Invested */
            invested: number;
            /** Gain */
            gain: number;
            /** Gain Pct */
            gain_pct: number | null;
            /** Day Change */
            day_change: number;
            /** Day Change Pct */
            day_change_pct: number | null;
            /** Realized Gain */
            realized_gain: number;
            /** Positions */
            positions: components["schemas"]["PositionOut"][];
            /** Sectors */
            sectors: components["schemas"]["SectorOut"][];
            counter: components["schemas"]["CounterOut"];
        };
        /** PositionOut */
        PositionOut: {
            /** Security Id */
            security_id: number;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Sector */
            sector: string | null;
            /** Kind */
            kind: string;
            /** Quantity */
            quantity: number;
            /** Avg Cost */
            avg_cost: number;
            /** Price */
            price: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** Value */
            value: number;
            /** Gain */
            gain: number;
            /** Gain Pct */
            gain_pct: number | null;
            /** Weight */
            weight: number;
        };
        /** RealTrackOut */
        RealTrackOut: {
            /** Picks */
            picks: number;
            /** Hit Rate */
            hit_rate: number;
            /** Hit After Fees */
            hit_after_fees: number;
            /** Mean Return */
            mean_return: number;
            /** Mean After Fees */
            mean_after_fees: number;
            /** Baseline Mean */
            baseline_mean: number;
            /** Edge */
            edge: number;
            /**
             * First Day
             * Format: date
             */
            first_day: string;
        };
        /** ScoreOut */
        ScoreOut: {
            /** Total */
            total: number | null;
            /** Technical */
            technical: number | null;
            /** Fundamental */
            fundamental: number | null;
            /** Available Ratio */
            available_ratio: number;
            /** Liquid */
            liquid: boolean;
            /** Eligible For Top */
            eligible_for_top: boolean;
            /** History Days */
            history_days: number;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Components */
            components: components["schemas"]["ComponentOut"][];
        };
        /** ScreenerRow */
        ScreenerRow: {
            /** Id */
            id: number;
            /** Yahoo Ticker */
            yahoo_ticker: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Market */
            market: string;
            /** Country */
            country: string | null;
            /** Sector */
            sector: string | null;
            /** Eligibility */
            eligibility: string;
            /** Price */
            price: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** Perf 1W */
            perf_1w: number | null;
            /** Perf 1M */
            perf_1m: number | null;
            /** Perf 1Y */
            perf_1y: number | null;
            /** Score */
            score: number | null;
            /** Pe */
            pe: number | null;
            /** Dividend Yield */
            dividend_yield: number | null;
            /** Liquid */
            liquid: boolean;
            /** Available Ratio */
            available_ratio: number | null;
            /** Isin */
            isin: string | null;
            /** Is Favorite */
            is_favorite: boolean;
            /** Sparkline */
            sparkline: number[];
        };
        /** SectorOut */
        SectorOut: {
            /** Sector */
            sector: string;
            /** Value */
            value: number;
            /** Weight */
            weight: number;
        };
        /** SecurityDetail */
        SecurityDetail: {
            /** Id */
            id: number;
            /** Yahoo Ticker */
            yahoo_ticker: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Market */
            market: string;
            /** Country */
            country: string | null;
            /** Sector */
            sector: string | null;
            /** Eligibility */
            eligibility: string;
            /** Price */
            price: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** Perf 1W */
            perf_1w: number | null;
            /** Perf 1M */
            perf_1m: number | null;
            /** Perf 1Y */
            perf_1y: number | null;
            /** Score */
            score: number | null;
            /** Pe */
            pe: number | null;
            /** Dividend Yield */
            dividend_yield: number | null;
            /** Liquid */
            liquid: boolean;
            /** Available Ratio */
            available_ratio: number | null;
            /** Isin */
            isin: string | null;
            /** Is Favorite */
            is_favorite: boolean;
            /** Sparkline */
            sparkline: number[];
            /** Industry */
            industry: string | null;
            /** Eligibility Source */
            eligibility_source: string;
            /** Currency */
            currency: string;
            /** As Of */
            as_of: string | null;
            fundamentals: components["schemas"]["FundamentalsOut"] | null;
            score_detail: components["schemas"]["ScoreOut"] | null;
        };
        /** SecurityForecastOut */
        SecurityForecastOut: {
            /** As Of */
            as_of: string | null;
            /** Signals */
            signals: components["schemas"]["SignalOut"][];
            /** Horizons */
            horizons: {
                [key: string]: components["schemas"]["HorizonForecastOut"] | null;
            };
        };
        /** SecurityItem */
        SecurityItem: {
            /** Id */
            id: number;
            /** Yahoo Ticker */
            yahoo_ticker: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Market */
            market: string;
            /** Country */
            country: string | null;
            /** Sector */
            sector: string | null;
            /** Eligibility */
            eligibility: string;
            /** Eligibility Source */
            eligibility_source: string;
            /** Eligibility Override */
            eligibility_override: string | null;
            /** Price */
            price: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** As Of */
            as_of: string | null;
        };
        /** SecurityList */
        SecurityList: {
            /** Items */
            items: components["schemas"]["SecurityItem"][];
            /** Total */
            total: number;
        };
        /** SettingsOut */
        SettingsOut: {
            /** Min Orders Per Year */
            min_orders_per_year: number;
            /** Penalty Fee */
            penalty_fee: number;
            /** Fee Grid */
            fee_grid: components["schemas"]["FeeTierIn"][];
        };
        /** SettingsUpdate */
        SettingsUpdate: {
            /** Min Orders Per Year */
            min_orders_per_year: number;
            /** Penalty Fee */
            penalty_fee: number;
            /** Fee Grid */
            fee_grid: components["schemas"]["FeeTierIn"][];
        };
        /** SignalOut */
        SignalOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Bullish */
            bullish: boolean;
        };
        /** SignalStatOut */
        SignalStatOut: {
            /** N */
            n: number;
            /** Mean */
            mean: number;
            /** Median */
            median: number;
            /** Hit Rate */
            hit_rate: number;
            /** Mean Excess */
            mean_excess: number;
            /** Beat Index */
            beat_index: number;
            /** Hit After Fees */
            hit_after_fees: number;
            /** Reliability */
            reliability: string;
        };
        /** SignalStatsOut */
        SignalStatsOut: {
            /** As Of */
            as_of: string | null;
            /** Computed At */
            computed_at: string | null;
            /** Round Trip Cost */
            round_trip_cost: number | null;
            /** Signals */
            signals: components["schemas"]["SignalStatsRowOut"][];
            /** Baseline */
            baseline: {
                [key: string]: components["schemas"]["SignalStatOut"] | null;
            };
        };
        /** SignalStatsRowOut */
        SignalStatsRowOut: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Description */
            description: string;
            /** Bullish */
            bullish: boolean;
            /** Horizons */
            horizons: {
                [key: string]: components["schemas"]["SignalStatOut"] | null;
            };
        };
        /** SimulationOut */
        SimulationOut: {
            /** Start Date */
            start_date: string | null;
            /** Start Price */
            start_price: number | null;
            /** Current Price */
            current_price: number | null;
            /** Shares */
            shares: number;
            /** Invested */
            invested: number;
            /** Buy Fee */
            buy_fee: number;
            /** Sell Fee */
            sell_fee: number;
            /** Current Value */
            current_value: number;
            /** Gain */
            gain: number;
            /** Gain Pct */
            gain_pct: number | null;
            /** Message */
            message: string | null;
        };
        /** StatusResponse */
        StatusResponse: {
            /** Market Open */
            market_open: boolean;
            /** Jobs */
            jobs: components["schemas"]["JobStatus"][];
            /** Indices */
            indices: components["schemas"]["IndexQuote"][];
        };
        /** TopItem */
        TopItem: {
            /** Id */
            id: number;
            /** Yahoo Ticker */
            yahoo_ticker: string;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Kind */
            kind: string;
            /** Market */
            market: string;
            /** Country */
            country: string | null;
            /** Sector */
            sector: string | null;
            /** Eligibility */
            eligibility: string;
            /** Price */
            price: number | null;
            /** Change Pct */
            change_pct: number | null;
            /** Perf 1W */
            perf_1w: number | null;
            /** Perf 1M */
            perf_1m: number | null;
            /** Perf 1Y */
            perf_1y: number | null;
            /** Score */
            score: number | null;
            /** Pe */
            pe: number | null;
            /** Dividend Yield */
            dividend_yield: number | null;
            /** Liquid */
            liquid: boolean;
            /** Available Ratio */
            available_ratio: number | null;
            /** Isin */
            isin: string | null;
            /** Is Favorite */
            is_favorite: boolean;
            /** Sparkline */
            sparkline: number[];
            /** Technical */
            technical: number | null;
            /** Fundamental */
            fundamental: number | null;
            /** Reasons */
            reasons: string[];
        };
        /** TrackRecordOut */
        TrackRecordOut: {
            /** Cutoff */
            cutoff: string | null;
            /** Round Trip Cost */
            round_trip_cost: number | null;
            /** Simulated */
            simulated: {
                [key: string]: components["schemas"]["BacktestOut"] | null;
            };
            /** Real */
            real: {
                [key: string]: components["schemas"]["RealTrackOut"] | null;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_securities_api_securities_get: {
        parameters: {
            query?: {
                q?: string | null;
                kind?: ("stock" | "etf" | "index") | null;
                eligibility?: ("eligible" | "a_verifier" | "non_eligible") | null;
                limit?: number;
                offset?: number;
                overridden?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_eligibility_api_securities__security_id__eligibility_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                security_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EligibilityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityItem"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_security_api_securities__security_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                security_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_api_securities__security_id__history_get: {
        parameters: {
            query?: {
                period?: "1D" | "1W" | "1M" | "6M" | "1Y" | "5Y";
            };
            header?: never;
            path: {
                security_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_news_api_securities__security_id__news_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                security_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulate_api_securities__security_id__simulate_get: {
        parameters: {
            query: {
                amount: number;
                period?: "1W" | "1M" | "6M" | "1Y";
            };
            header?: never;
            path: {
                security_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusResponse"];
                };
            };
        };
    };
    get_screener_api_screener_get: {
        parameters: {
            query?: {
                kind?: ("stock" | "etf") | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenerRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_top_api_rankings_top_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_movers_api_rankings_movers_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Movers"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_heatmap_api_market_heatmap_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HeatmapItem"][];
                };
            };
        };
    };
    estimate_fee_api_fees_estimate_get: {
        parameters: {
            query: {
                amount: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeeEstimate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_favorite_api_favorites__security_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                security_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_favorite_api_favorites__security_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                security_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_settings_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    update_settings_api_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_orders_api_orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"][];
                };
            };
        };
    };
    create_order_api_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_order_api_orders__order_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_order_api_orders__order_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_counter_api_orders_counter_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CounterOut"];
                };
            };
        };
    };
    get_portfolio_api_portfolio_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioOut"];
                };
            };
        };
    };
    get_portfolio_history_api_portfolio_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPointOut"][];
                };
            };
        };
    };
    read_assistant_settings_api_assistant_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantSettingsOut"];
                };
            };
        };
    };
    update_assistant_settings_api_assistant_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssistantSettingsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_api_assistant_conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"][];
                };
            };
        };
    };
    create_conversation_api_assistant_conversations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversation_api_assistant_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_api_assistant_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_assistant_conversations__conversation_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_forecasts_api_forecasts_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ForecastListOut"];
                };
            };
        };
    };
    signal_statistics_api_forecasts_signals_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalStatsOut"];
                };
            };
        };
    };
    track_record_api_forecasts_track_record_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackRecordOut"];
                };
            };
        };
    };
    security_forecast_api_securities__security_id__forecast_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                security_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SecurityForecastOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    robots_api_seo_robots_txt_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    sitemap_api_seo_sitemap_xml_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    llms_api_seo_llms_txt_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
