"""forecasts

Revision ID: 75e519660560
Revises: 8689643dcd0c
Create Date: 2026-09-27 15:19:54.044525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '75e519660560'
down_revision: Union[str, Sequence[str], None] = '8689643dcd0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_until', sa.Date(), nullable=True),
    sa.Column('cutoff', sa.Date(), nullable=True),
    sa.Column('round_trip_cost', sa.Float(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('backtest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('horizon', sa.String(length=2), nullable=False),
    sa.Column('expected_return', sa.Float(), nullable=False),
    sa.Column('prob_up', sa.Float(), nullable=False),
    sa.Column('reliability', sa.String(length=8), nullable=False),
    sa.Column('signals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('base_close', sa.Float(), nullable=False),
    sa.Column('actual_return', sa.Float(), nullable=True),
    sa.Column('resolved_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'as_of', 'horizon', name='uq_forecast_security_day_horizon')
    )
    op.create_index('ix_forecasts_as_of_horizon', 'forecasts', ['as_of', 'horizon'], unique=False)
    op.create_index(op.f('ix_forecasts_security_id'), 'forecasts', ['security_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecasts_security_id'), table_name='forecasts')
    op.drop_index('ix_forecasts_as_of_horizon', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_table('forecast_runs')
    # ### end Alembic commands ###
