"""assistant settings

Revision ID: b4c5c25ef2d8
Revises: cfd399037de6
Create Date: 2026-09-26 21:24:28.984873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c5c25ef2d8'
down_revision: Union[str, Sequence[str], None] = 'cfd399037de6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('anthropic_key_enc', sa.Text(), nullable=True))
    op.add_column('user_settings', sa.Column('ai_model', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'ai_model')
    op.drop_column('user_settings', 'anthropic_key_enc')
    # ### end Alembic commands ###
