"""scores and favorites

Revision ID: e2a20d8705c8
Revises: d132b530c4d9
Create Date: 2026-09-26 15:03:00.950486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e2a20d8705c8'
down_revision: Union[str, Sequence[str], None] = 'd132b530c4d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'security_id')
    )
    op.create_table('scores',
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('technical', sa.Float(), nullable=True),
    sa.Column('fundamental', sa.Float(), nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('available_ratio', sa.Float(), nullable=False),
    sa.Column('liquid', sa.Boolean(), nullable=False),
    sa.Column('history_days', sa.Integer(), nullable=False),
    sa.Column('avg_turnover_eur', sa.Float(), nullable=False),
    sa.Column('eligible_for_top', sa.Boolean(), nullable=False),
    sa.Column('perf_1w', sa.Float(), nullable=True),
    sa.Column('perf_1m', sa.Float(), nullable=True),
    sa.Column('perf_3m', sa.Float(), nullable=True),
    sa.Column('perf_1y', sa.Float(), nullable=True),
    sa.Column('sparkline', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('security_id')
    )
    op.create_index(op.f('ix_scores_eligible_for_top'), 'scores', ['eligible_for_top'], unique=False)
    op.create_index(op.f('ix_scores_total'), 'scores', ['total'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scores_total'), table_name='scores')
    op.drop_index(op.f('ix_scores_eligible_for_top'), table_name='scores')
    op.drop_table('scores')
    op.drop_table('favorites')
    # ### end Alembic commands ###
